# Generated by Django 4.0.4 on 2022-06-30 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('talle_accesorio', models.IntegerField()),
                ('color_accesorio', models.CharField(max_length=70)),
                ('es_para_regalo', models.BooleanField(default=True)),
                ('imagen_accesorio', models.ImageField(upload_to='imagenes_accesorios')),
            ],
            options={
                'verbose_name': 'Accesorio',
                'verbose_name_plural': 'Accesorios',
            },
        ),
    ]
