# Generated by Django 4.0.4 on 2022-07-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesorios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesorio',
            old_name='color_accesorio',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='accesorio',
            old_name='es_para_regalo',
            new_name='es_resistente_agua',
        ),
        migrations.RemoveField(
            model_name='accesorio',
            name='talle_accesorio',
        ),
        migrations.AddField(
            model_name='accesorio',
            name='precio',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
