# Generated by Django 4.0.4 on 2022-07-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesorios', '0002_rename_color_accesorio_accesorio_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesorio',
            name='imagen_accesorio',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_accesorios'),
        ),
    ]
