# Generated by Django 4.0.4 on 2022-06-07 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ropa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prenda',
            old_name='tipo',
            new_name='tipo_prenda',
        ),
        migrations.AlterField(
            model_name='tipo',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
