# Generated by Django 4.0.4 on 2022-06-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ropa', '0002_rename_tipo_prenda_tipo_prenda_alter_tipo_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenda', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
                ('fecha_pedido', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
        migrations.RemoveField(
            model_name='prenda',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='prenda',
            name='tipo_prenda',
        ),
        migrations.AddField(
            model_name='prenda',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
