# Generated by Django 4.0.4 on 2022-06-07 06:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ropa', '0003_pedido_delete_tipo_remove_prenda_precio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='prenda',
            options={'verbose_name': 'Prenda', 'verbose_name_plural': 'Prendas'},
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
