# Generated by Django 4.0.4 on 2022-06-27 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ropa', '0005_accesorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='es_temporada_actual',
            field=models.BooleanField(default=True),
        ),
    ]
