# Generated by Django 4.0.4 on 2022-06-27 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ropa', '0006_pedido_es_temporada_actual'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesorio',
            old_name='para_regalo',
            new_name='es_para_regalo',
        ),
    ]
