# Generated by Django 4.0.4 on 2022-06-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ropa', '0007_rename_para_regalo_accesorio_es_para_regalo'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesorio',
            name='imagen_accesorio',
            field=models.ImageField(default='', upload_to='imagenes_accesorios'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='imagen_pedido',
            field=models.ImageField(default='', upload_to='imagenes_pedidos'),
            preserve_default=False,
        ),
    ]
