# Generated by Django 4.0.4 on 2022-06-30 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ropa', '0008_accesorio_imagen_accesorio_pedido_imagen_pedido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accesorio',
        ),
    ]
