# Generated by Django 4.0.4 on 2022-07-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ropa', '0009_delete_accesorio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='es_temporada_actual',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='imagen_pedido',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='prenda',
            name='talle',
        ),
        migrations.AddField(
            model_name='pedido',
            name='color',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='talle',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='tiene_estampado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prenda',
            name='es_temporada_actual',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='prenda',
            name='imagen_prenda',
            field=models.ImageField(default=1, upload_to='imagenes_prendas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prenda',
            name='precio',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prenda',
            name='tipo_tela',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
