# Generated by Django 4.0.4 on 2022-07-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ropa', '0010_remove_pedido_es_temporada_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='prenda',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
