# Generated by Django 4.0.4 on 2022-07-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ropa', '0011_alter_pedido_prenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='imagen_pedido',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_pedidos'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='prenda',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prenda',
            name='imagen_prenda',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_prendas'),
        ),
    ]
