# Generated by Django 4.0.4 on 2022-07-03 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ropa', '0012_pedido_imagen_pedido_alter_pedido_prenda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenda',
            name='nombre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
