# Generated by Django 4.0.4 on 2022-07-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_profile_description_user_profile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='chosen_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='perfil_prueba.jpg', null=True, upload_to='profile_picture'),
        ),
    ]
