# Generated by Django 4.0.4 on 2022-07-05 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_profile_email_alter_user_profile_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='surname',
        ),
    ]
